import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>next food random</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-4xl text-slate-800">คิดไม่ออกจะกินอะไรดี🥗</h1>
        <h3 className="text-lg">งั้นไม่ต้องคิด สุ่มเอา</h3>
        <div className="bg-zinc-100 p-3 rounded border border-zinc-300 my-3">
          <div className="text-center text-lg text-yellow-800">TODOs (soon)</div>
          <div>● อยากให้แชร์เมนูแล้วใส่ภาพตัวอย่างใน meta tag ได้</div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
